language: node_js
node_js: 14
branches:
  only: main
install:
  - yarn
script:
  - yarn build
  - yarn test
deploy:
  api_key:
    secure:
  email: npmjs@charlesstover.com
  on:
    branch: main
  provider: npm
  skip_cleanup: true
